# Project configuration

ASSETS = ["Gold", "Bitcoin", "NVIDIA"]

DEFAULT_SMA_PERIOD = 20
DEFAULT_EMA_PERIOD = 20

DEFAULT_ROLLING_WINDOW = 30

TRADING_DAYS_PER_YEAR = 252

INITIAL_CAPITAL = 100000.0

TRANSACTION_COST = 0.001

RISK_FREE_RATE = 0.0